# Generated by Django 4.2.3 on 2023-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('place', models.CharField(max_length=300, verbose_name='Область применения')),
                ('facturer', models.CharField(max_length=150, verbose_name='Производитель')),
                ('descripton', models.CharField(max_length=300, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
