# Generated by Django 4.2.3 on 2023-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facturer_сountry',
            field=models.CharField(default='', max_length=150, verbose_name='Страна производителя'),
        ),
    ]
