# Generated by Django 4.2.3 on 2023-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0002_product_facturer_сountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripton',
            field=models.CharField(max_length=300, verbose_name='Примечание'),
        ),
    ]
