# Generated by Django 4.2.3 on 2023-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0003_alter_product_descripton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
