# Generated by Django 4.2.3 on 2023-07-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0006_alter_product_image_alter_product_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnails',
        ),
    ]
